### ISSUE TITLE
Error messages on drives that are not seeded

### ISSUE THREAD

**Issue by rzelnik** [hypercore-protocol/cli#22]
I receive strange errors in 'hyp info' command on hyperdrives that are inaccessible / not seeded well.

Error: Block not available from peers
    at Object.decode (/usr/lib/node_modules/@hyperspace/cli/node_modules/@hyperspace/rpc/index.js:11:17)
    at RPC._onmessage (/usr/lib/node_modules/@hyperspace/cli/node_modules/arpeecee/index.js:113:33)
    at Parser._nextState (/usr/lib/node_modules/@hyperspace/cli/node_modules/arpeecee/parser.js:127:14)
    at Parser._readMessage (/usr/lib/node_modules/@hyperspace/cli/node_modules/arpeecee/parser.js:54:19)
    at Parser.recv (/usr/lib/node_modules/@hyperspace/cli/node_modules/arpeecee/parser.js:35:44)
    at RPC._write (/usr/lib/node_modules/@hyperspace/cli/node_modules/arpeecee/index.js:170:22)
    at WritableState.update (/usr/lib/node_modules/@hyperspace/cli/node_modules/streamx/index.js:168:14)

IMHO unavailability of a hyperdrive should be considered and treated as normal situation. I would expect information in 'hyp info' like this:

06e4fa..ff (hyperdrive): 0 connected | [↓0 B/s ↑0 B/s] - Not seeding, drive data inaccessible/incomplete

**Comment by rzelnik** [comment]
No more relevant - after update the 'hyp info" behaviour changed and the error disappeared.
