### ISSUE TITLE
Error on bee create

### ISSUE THREAD

**Issue by pfrazee** [hypercore-protocol/cli#30]
```
C:\Users\abusn>hyp create bee
Bee Created: hyper://1a516a871719c7e9162368be8e945a47d60df42929f6027aff62493942f36e84
events.js:292
      throw er; // Unhandled 'error' event
      ^
 
Error: key is required
    at Object.encodingLength (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\hyperspace-mirroring-service\rpc\messages.js:52:34)
    at Parser.send (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\arpeecee\parser.js:138:24)
    at RPC._push (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\arpeecee\index.js:159:25)    at RPC._request (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\arpeecee\index.js:203:10)
    at Method.request (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\arpeecee\index.js:247:29)
    at HRPCServiceMirror.mirror (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\hyperspace-mirroring-service\rpc\index.js:63:25)
    at HyperspaceMirroringClient.mirror (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\hyperspace-mirroring-service\client.js:57:32)
    at command (file:///C:/Users/abusn/AppData/Roaming/npm/node_modules/@hyperspace/cli/lib/commands/create.js:25:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.obj.command (file:///C:/Users/abusn/AppData/Roaming/npm/node_modules/@hyperspace/cli/bin/hyp.js:101:7)
Emitted 'error' event on HRPCSession instance at:
    at RPC.<anonymous> (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\hyperspace-mirroring-service\rpc\index.js:117:101)
    at RPC.emit (events.js:327:22)
    at WritableState.afterDestroy (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\streamx\index.js:439:19)
    at RPC._destroy (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\arpeecee\index.js:190:5)
    at WritableState.updateNonPrimary (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\streamx\index.js:187:16)
    at WritableState.update (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\streamx\index.js:172:70)
    at updateWriteNT (C:\Users\abusn\AppData\Roaming\npm\node_modules\@hyperspace\cli\node_modules\streamx\index.js:479:6)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
```

**Comment by pfrazee** [comment]
Fixed in 1.3.2
