### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by hiswillbedun** [hypercore-protocol/cli#35]
I have installed, removed and reinstalled hyp and still getting same error.   When installing, I receive several warnings about deprecated components.   However it finishes install.   Once I enter hyp daemon start or any other command beginning with hyp, I get the following.   OS is KDE Neon 5.20.

```hyp daemon start    
/usr/local/lib/node_modules/@hyperspace/cli/bin/hyp.js:6
import subcommand from 'subcommand'
       ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)```

Here are the warnings I get while installing.

```$ sudo npm install -g @hyperspace/cli
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/usr/local/bin/hyp -> /usr/local/lib/node_modules/@hyperspace/cli/bin/hyp.js

> fd-lock@1.1.1 install /usr/local/lib/node_modules/@hyperspace/cli/node_modules/fd-lock
> node-gyp-build```

Any assistance would be greatly appreciated!

**Comment by pfrazee** [comment]
Hi, sorry for the delay- are you using node 14+? That's required. Latest hyp cli release will now tell you if you're using too old a node version.

**Comment by hiswillbedun** [comment]
I am actually using the latest version available.  was 15.x

**Comment by pfrazee** [comment]
Hmm, that's surprising. I'm not sure why you'd see that error then.

**Comment by hiswillbedun** [comment]
Was actually giving thought to wiping my system due to other issues and
installing fresh.   You can close the ticket for now.  If I still have
issues, I will reopen it.

**Comment by pfrazee** [comment]
Okay, if anybody else experiences this please reopen!
